

db.define_table('activity',
                Field('activity', 'string', label='Activity'),
                Field('details', 'text', label='Details'),
                Field('forename', 'string', label='First Name'),
                Field('surname', label='Surname'),
                Field('organisation', label='Organisation'),
                Field('orgtype', label='Organisation Type'),
                Field('town', label='nearest town or city'),
                Field('subdivision', label='area/subdivision'),
                Field('country', label='country'),
                Field('continent', label='continent'),
                Field('coord', 'string', label='Lat/Longitude'),
                Field('question_long', 'double', default=0.0, label='Latitude', writable=False, readable=False),
                Field('question_lat', 'double', default=0.0, label='Longitude', writable=False, readable=False),
                Field('auth_userid', 'reference auth_user', writable=False, label='Submitter', default=auth.user_id),
                Field('status', 'string', default='In Progress',
                      requires=IS_IN_SET(['Draft', 'Complete',  'Rejected']),
                      comment='Select draft to defer for later editing'),
                Field('createdate', 'datetime', writable=False, label='Date Created', default=request.utcnow),
                Field('submitdate', 'datetime', writable=False, label='Date Completed'),
                Field('category', 'string', default='Unspecified', label='Category'),
                Field('rating', 'decimal(6,2)', default=5, writable=False, label='We feel'),
                Field('impact', 'decimal(6,2)', default=5, writable=False, label='Importance'),
                Field('tags', 'list:string'),
                Field('numratings', 'integer', default=0)
                )
